- package.json
- src/app.js
- yarn.lock
Express by default does not always handle async/await errors, resulting
in an unhandled error and a crashed server.
This fix uses the express-async-errors library to monkepatch the Express
framework to handle the errors.
> fix: Handle async errors

- .github/workflows/checks.yml
bugfix: Add missing env for sonarcloud integration
> BAU-fix-github-sonarcloud-integration

- src/app/details/controllers/done.js
- src/app/details/controllers/done.test.js
- src/app/kbv/controllers/load-question.js
- src/app/kbv/controllers/question.js
- test/mocks/mappings/questions-error.json
- test/mocks/mappings/questions.json
The common API code uses `session_id` instead of `sessionId`. This PR renames all usages to the new format.
> fix: rename sessionId to session_id to match common code

- src/app/kbv/controllers/done.js
- src/app/kbv/controllers/load-question.js
- src/app/kbv/controllers/question.js
- test/mocks/mappings/questions.json
Use `snake_case` `session_id` for auth calls, and `kebab-case` `session-id` for KBV CRI specific calls.
> fix: Rename session-id to session_id for non-auth endpoints

- .github/workflows/checks.yml
- test/browser/features/kbv.feature
- test/browser/pages/index.js
- test/browser/pages/relying-party.js
- test/browser/step_definitions/details.js
Restore browser tests by linking directly into the oauth path, as opposed to requiring core-stub.
This means they are not currently dual purpose and can not be run against an environment.
But it does mean there are browser tests that can be run.
> fix: Use browser tests without core-stub

- Dockerfile
Create Dockerfile suitable for deployment to Fargate: ECS 
New Dockerfile created on node:16.14.2-alpine3.15, tested locally
Required for migration
- [KBV-457](https://govukverify.atlassian.net/browse/KBV-457)
> [KBV-457] Dockerfile for fargate deployment

- package.json
- src/app.js
- src/app/kbv/steps.js
- src/lib/config.js
- src/lib/settings.js
- src/lib/settings.test.js
- test/browser/pages/relying-party.js
- test/mocks/mappings/questions.json
- yarn.lock
- Update usage of common express middleware so as to use the new
authorization code endpoint
- Redirect from done to /oauth/callback when done
This updates `kbv-front` to use the common code for retrieving the `authorization code`. 
> feat: Use authorization code from common-express

- package.json
- test/mocks/mappings/questions.json
- yarn.lock
Update to use v0.0.7 of `common-express` which uses a `GET` not a `POST` for `authorization`
> chore: Bump package version v0.0.7

- src/app/kbv/controllers/question.js
- src/app/kbv/controllers/question.test.js
If the response from the question or answer endpoints returns an error, then the error response was not being handled correctly, and the server was crashing.
The correct way to deal with this is to return from the middleware with any error, and let Express handle it only once.
Test coverage was also increased.
> fix: Server crash & increase test coverage

- src/app/kbv/controllers/question.js
- src/app/kbv/controllers/question.test.js
- src/lib/dynamic-i18n.js
- src/lib/dynamic-i18n.test.js
Restore #109 over the top of more extensive testing, including unit tests and API validation.
---
The previous dynamic question code was buggy, and didn't actually use the i18n files.
This refactor (without tests!) uses i18n content if found, and has a fallback of the dynamic API content.
Answers are not found in i18n content, so are passed through directly.
Browser tests show that this is passing, as does manual testing. Improved unit tests will appear in a future PR.
- [KBV-504](https://govukverify.atlassian.net/browse/KBV-504)
> feat: Rework translation approach from override to fallback

- deploy/template.yaml
- Changed `API_BASE_URL` environment variable to refer to the new kbv stack private gateway id
- To enable testing in the staging environment
- [OJ-945](https://govukverify.atlassian.net/browse/OJ-945)
> OJ-945 - temporarily refer to the kbv stacks

- deploy/template.yaml
- Modify API_BASE_URL to use the new kbv private gateway id
- Use the new kbv stacks
- [OJ-945](https://govukverify.atlassian.net/browse/OJ-945)
> OJ-945 - reference new kbv private gateway id

- src/app/kbv/controllers/abandon.js
- src/app/kbv/controllers/abandon.test.js
- src/app/kbv/controllers/load-question.js
- src/app/kbv/controllers/question.js
- src/app/kbv/controllers/question.test.js
- test/mocks/mappings/questions.json
There is currently an inconsistency with the common API endpoints - some of them use `session-id` and some of them use `session_id`.
In order to non-breaking refactoring on the API - all the API requests will temporarily provide both parameters. Once the refactoring is complete, the unused parameter can be removed.
- [OJ-962](https://govukverify.atlassian.net/browse/OJ-962)
> refactor: Send session_id & session-id for BE refactoring

- src/lib/dynamic/question.js
- src/lib/dynamic/question.test.js
- src/locales/cy/default.yml
- src/locales/en/default.yml
The KBV CRI mostly displays dynamic questions. This change sets a default validation message for all required fields. The only other field in this CRI is on the abandon page, and that already has a required message set.
This approach of overriding the default will allow for individual questions to have their own validation message if needed.
> refactor: Use global required validator for question

- src/presenters/question-to-hint.js
- src/presenters/question-to-hint.test.js
- src/presenters/question-to-legend.js
- src/presenters/question-to-legend.test.js
- src/presenters/question-to-radios.js
- src/presenters/question-to-radios.test.js
`hmpo-i18n` returns empty strings for missing keys, and `i18next` returns the keys.
This PR returns the appropriate hint or title for both libraries.
It also should fix the issue with a locales file wanting to override a hint text with no value.
> Fix missing translations behaviour

- package.json
- src/app.js
- src/locales/cy/fields.yml
- src/locales/cy/pages.yml
- src/locales/en/fields.yml
- src/locales/en/pages.yml
- src/views/kbv/abandon.html
- src/views/kbv/question.html
- yarn.lock
Switch from using hmpo-i18n to i18next so that we can take advantage of cookie domains and interpolation.
This PR uses the i18next middleware exported from common-express, and updates templates with the minimal changes required to use the new library.
It also contains the cookie domain setting. 
> Use i18next

- deploy/template.yaml
Three CloudWatch alarms for the Address CRI frontend hosted on ECS. Alarm when:
ECS tasks lower than 1 over 2 minutes - there are no tasks running
ECS tasks lower than 2 over 15 minutes - there should be two tasks running
More than 1 ELB 5XX error every minute over 5 minutes
- [OJ-1007](https://govukverify.atlassian.net/browse/OJ-1007)
> OJ-1007 KBV frontend CloudWatch Alarms

- README.md
This change, somewhat to my surprise has broken the team manual.
Turns out the slight misformatting in the markdown is getting slurpped up by the team manual for [pages like
this](https://di-team-manual.london.cloudapps.digital/code/di-ipv-cri-address-front/index.html#di-ipv-cri-address-front).
Which in turn is then getting checked with html-proofer. Which reports the markdown error as a bad link and errors.
This means the team manual isn't building and can't be deployed.
This is a bit of an odd situation. Quick fix is to amend the markdown here. But I think in the long run we should stop html-proofer from checking everyone's README pages, if they're broken that should be down to teams to fix!
See [1] & [2]
[1]: https://gds.slack.com/archives/CAC6S0UHK/p1667583411670329
[2]: …
> BAU: Fix link in readme markdown

- deploy/template.yaml
Added initial WAF template to block all unhandled paths to the front end load balancer and public API rest gateway 
To prevent attacks as per incident 59 - 2022-11-10 P4 CRI Cyber Security Incident Incident 
- [Incident Report 59](https://docs.google.com/document/d/1_ykKlV4DsO9CmmMypwWt6ZWfV99scaxT/edit?userstoinvite=john.pearce%40digital.cabinet-office.gov.uk&actionButton=1#heading=h.gjdgxs)
- [OJ-1103](https://govukverify.atlassian.net/browse/OJ-1103)
Promotion to Integration and Production disabled to allow full testing beforehand
[OJ-1103]: https://govukverify.atlassian.net/browse/OJ-1103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1103 initial waf excluding owasp

- src/locales/cy/default.yml
- src/locales/cy/pages.yml
- src/locales/en/default.yml
- src/locales/en/pages.yml
The product name is being changed from **GOV.UK Account** to **GOV.UK One Login**. The code in this PR updates any appearance of the name in the source code, including content which may be hidden from the user (e.g the cookie banner).
`locales/en/default.yml` and `locales/en/pages.yml` have been updated.
The user should see a consistent name for the service throughout their journey.
- [PYIC-2282](https://govukverify.atlassian.net/browse/PYIC-2282) - a subticket of [PYIC-2249](https://govukverify.atlassian.net/browse/PYIC-2249) for the journey-wide epic.
[PYIC-2282]: https://govukverify.atlassian.net/browse/PYIC-2282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PYIC-2249]: https://govukverify.atlassian.net/browse/PYIC-2249?atlOrigin=eyJpIjoiN …
> PYIC-2249 Update service name

- deploy/template.yaml
Added load balancer to exports
The WAF template needs to be able to import the load balancer ARN to create the web ACL association 
- [OJ-1103](https://govukverify.atlassian.net/browse/OJ-1103)
[OJ-1103]: https://govukverify.atlassian.net/browse/OJ-1103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> oj-1103 kbv front exported load balancer arn

- package.json
- yarn.lock
Revert "BAU: Bump lint-staged from 13.0.3 to 13.2.3"
This reverts commit 3c3a584aeb3753719bc3111f1c4d520e98efec18.
This is for testing purposes.
modified:   package.json
modified:   yarn.lock
I am not sure if this is somehow effecting DNS Resolution. 
> Revert "BAU: Bump lint-staged from 13.0.3 to 13.2.3"

- .secrets.baseline
Added `secretsmanager|SecretString` to `keyword_exclude` because the detect-secrets scan will always fail when the word contains "secret" so when referencing something like  SecretsManager in the template.yaml it'll complain. Whenever we modify the template.yaml we are then always required to run secrets-baseline scan since the line numbers change.
> BAU: Added `secretsmanager|SecretString` to `keyword_exclude`

- package.json
- yarn.lock
- update govukfrontend-4.8
- update ipv-cri-common-express 5.1
- [OJ-2284](https://govukverify.atlassian.net/browse/OJ-2284)
[OJ-2284]: https://govukverify.atlassian.net/browse/OJ-2284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Use tudor crown

- package.json
- src/app/kbv/controllers/abandon.js
- src/app/kbv/controllers/abandon.test.js
- src/app/kbv/controllers/load-question.js
- src/app/kbv/controllers/load-question.test.js
- src/app/kbv/controllers/question.js
- src/app/kbv/controllers/question.test.js
- test/utils/mocha-helpers.js
- yarn.lock
- add new node package frontend-passthrough-headers
- add personal data headers to all api calls
- 
This changes are required to enable delivery of the TxMA headers initiative in time for scaled traffic with HMRC onboarding, which is required to realise the fraud benefits for the OL programme. 
- [DFC-574](https://govukverify.atlassian.net/browse/DFC-574)
[DFC-574]: https://govukverify.atlassian.net/browse/DFC-574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DFC-574: add personal data headers to all api calls

- deploy/template.yaml
Enabled waf association for cloudfront testing in dev and build
To enable the cloudfront distribution
- [IPS-739](https://govukverify.atlassian.net/browse/IPS-739)
[IPS-739]: https://govukverify.atlassian.net/browse/IPS-739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-739 enable cloudfront for KBV dev and build

- deploy/template.yaml
Enabled waf association for cloudfront  in staging and integration
To enable the cloudfront distribution
- [IPS-739](https://govukverify.atlassian.net/browse/IPS-739)
[IPS-739]: https://govukverify.atlassian.net/browse/IPS-739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-739 enable KBV waf association staging and integration

- package.json
- src/app.js
- yarn.lock
Replace aws-sdk with @aws-sdk/client-dynamodb
aws-sdk is reaching end of life
- [OJ-2686](https://govukverify.atlassian.net/browse/OJ-2686)
[OJ-2686]: https://govukverify.atlassian.net/browse/OJ-2686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2686: Replace aws-sdk with @aws-sdk/client-dynamodb

- deploy/template.yaml
IPS-536 Canary ECS Deployments for KBV - Rollout
This PR must not be merged until previous Canary PR is merged.
This shifts the TaskDefinition to go via the Canary Deployment but this
only occurs once the bluegreen nested stack is deployed.
modified:   deploy/template.yaml
- [IPS-536](https://govukverify.atlassian.net/browse/IPS-536)
[IPS-536]: https://govukverify.atlassian.net/browse/IPS-536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-536 Canary ECS Deployments for KBV - Rollout

- deploy/template.yaml
IPS-536 Canary Implementation Extras
Made the Network and LoadBalancer Configuration for AWS::ECS::SERVICE optional based on canary deployment, this is a cosmetic change for future edits to show that these settings only apply if not using canary deployments.
modified:   deploy/template.yaml
- [IPS-536](https://govukverify.atlassian.net/browse/IPS-536)
[IPS-536]: https://govukverify.atlassian.net/browse/IPS-536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-536 Canary Implementation Extras

- src/app.js
Created a new handler to redirect to error page when `redirect_uri` is undefined.
The fix has been taken from [bav-front](https://github.com/govuk-one-login/ipv-cri-bav-front/blob/5f3f22a211b1a3cd38d36d40b75083d0a5053c91/src/app.js#L160)
An exception is being thrown in the code when the `redirect_uri` is undefined: `/kbv/question Cannot read properties of undefined (reading 'redirect_uri')` and because of this exception, users are not routed to an appropriate error screen.
- [OJ-2724](https://govukverify.atlassian.net/browse/OJ-2724)
[OJ-2724]: https://govukverify.atlassian.net/browse/OJ-2724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2724: render error page if `redirect_uri` is not present

- src/app.js
Reverts govuk-one-login/ipv-cri-kbv-front#1062
This PR did not work and the fix will now be implemented in common-express as it's effecting multiple CRIs. 
https://github.com/govuk-one-login/ipv-cri-common-express/pull/398
> Revert "OJ-2724: render error page if `redirect_uri` is not present"

- package.json
- yarn.lock
common-express updated to 7.0.0
Bug fix for the `redirect_uri` being undefined
- [OJ-2724](https://govukverify.atlassian.net/browse/OJ-2724)
[OJ-2724]: https://govukverify.atlassian.net/browse/OJ-2724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2724: Update common-express to 7.0.0

- test/browser/cucumber.js
Remove cucumber publish quiet
It's been deprecated as per the [docs](https://github.com/cucumber/cucumber-js/blob/main/docs/deprecations.md)
> BAU: Remove cucumber publish quiet

- deploy/template.yaml
Adds missing RetentionInDays to log group
So that they are not retained for infinity
- [OJ-2600](https://govukverify.atlassian.net/browse/OJ-2600)
[OJ-2600]: https://govukverify.atlassian.net/browse/OJ-2600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2600: Adds missing RetentionInDays to log group

- src/app/kbv/controllers/question.js
- src/app/kbv/controllers/question.test.js
see: [OJ-2777](https://govukverify.atlassian.net/browse/OJ-2777)
This PR handles TypeError that can occur in the Question Controller,  the error `Cannot read properties of undefined (reading 'questionID')` in dynatrace the error is now caught and explicitly handled.
It is suspected that the user maybe on this Question page for longer than expected
the error is likely to occur when they click continue.
It is also possible for the error to occur during Question Controller configure, so this has been replicated in code and handled as well.
During logging it is expected that TypeError would not occur, but these handled errors and it will be possible to determine exactly what point this error occurs i.e. in the Question Controller `save` or `configure`.
If TypeError due to Question not …
> OJ-2777: Fix TypeError on saving a non-existent question

- .github/workflows/post-merge-to-build.yml
- .github/workflows/post-merge-to-dev.yml
Update workflows to do the container signing and removed misleading empty region configuration from sam commands
Container signing is now enforced so deployments will fail without
- [IPS-1123](https://govukverify.atlassian.net/browse/IPS-1123)
[IPS-1123]: https://govukverify.atlassian.net/browse/IPS-1123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-1123 Use dev-platform action to sign images

- package.json
- yarn.lock
Upgrade dependencies that have a vulnerable version of semver
https://github.com/govuk-one-login/ipv-cri-kbv-front/security/dependabot/30
> Upgrade dependencies that use semver

- package.json
- yarn.lock
Removes yarn-audit-fix because it's not something that we actually need and it contains a vulnerability
https://github.com/govuk-one-login/ipv-cri-address-front/security/dependabot/55
- [OJ-2900](https://govukverify.atlassian.net/browse/OJ-2900)
[OJ-2900]: https://govukverify.atlassian.net/browse/OJ-2900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2900: Removes vulnerable package

- deploy/template.yaml
Turn off UA as it is no longer being used.
There will be subsequent tickets to deprecate but this is just to turn off as it causes a console error with new versions of the `@govuk-one-login/frontend-analytics` package.
> Turn off UA as it is no longer being used

- package.json
- yarn.lock
Bump govuk-frontend to version 4.9.0
There have been changes to crown logo.
- [OJ-2914](https://govukverify.atlassian.net/browse/OJ-2914)
[OJ-2914]: https://govukverify.atlassian.net/browse/OJ-2914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> build: bump govuk-frontend to version 4.9.0

- package.json
- src/app.js
- yarn.lock
Added overload-protection library to app.js
To prevent node from accepting too many connections and putting itself into a blocking state.
- [OJ-2864](https://govukverify.atlassian.net/browse/OJ-2864)
[OJ-2864]: https://govukverify.atlassian.net/browse/OJ-2864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2864: Add overload-protection

- deploy/template.yaml
Add responseLatency to API GW log settings
To see exact frontend latency
- [OJ-2965](https://govukverify.atlassian.net/browse/OJ-2965)
[OJ-2965]: https://govukverify.atlassian.net/browse/OJ-2965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2965: Add responseLatency to API GW log settings

- package.json
- test/utils/mocha-helpers.js
- yarn.lock
- Upgraded express to fix https://github.com/govuk-one-login/ipv-cri-kbv-front/security/dependabot/55
- Upgraded mocha to fix https://github.com/govuk-one-login/ipv-cri-kbv-front/security/dependabot/56
- Removed `reqres` package and replaced with mocks as it contains a number of vulnerable dependencies
The package is not fit for use because it is not being actively maintained
- [OJ-2920](https://govukverify.atlassian.net/browse/OJ-2920)
[OJ-2920]: https://govukverify.atlassian.net/browse/OJ-2920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2920: Vulnerability upgrades

- deploy/template.yaml
We need to have a 5XX Alarm (P1) if more than 80% of your traffic is returning 5XX in 2 of 5 datapoints to ensure that the team is aware if there is an high volume of 5XX errors, please implement an alarm similar to the following that will raise a critical alert if the volume of 5XXs is likely to mean a significant loss of service that would manifest as a service outage.
Added new Alarm definition for the above in Experian-cri
The invocation have been adjusted based on observed, traffic last [90days](https://gds.splunkcloud.com/en-GB/app/gds-050-digital-Identity/search?dispatch.sample_ratio=1&display.page.search.mode=smart&workload_pool=standard_perf&q=search%20index%3D%22gds_di_production%22%20source%3D%22*kbv-cri-front-*%22%20sourcetype%3D%22aws%3Acloudwatchlogs%3Aapi-access-*%22%20di_ac …
> OJ-2872: Add 5xx FE Api Gateway 80 percent error alarm

- src/app.js
Increased maxEventLoopDelay
It looks like the threshold has been set too low which is causing the 503s. Core have seen spikes that aren’t being logged by the vital signs package so where they have the same average event loop delay as us they have set the max to 400 and are not seeing any issues. 
We have made this change in address in it is reducing the number of 503s
- [OJ-2992](https://govukverify.atlassian.net/browse/OJ-2992)
[OJ-2992]: https://govukverify.atlassian.net/browse/OJ-2992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2992: Increase maxEventLoopDelay

- package.json
- yarn.lock
bump hmpo-components again
To fix build command
Before
After
- [OJ-2830](https://govukverify.atlassian.net/browse/OJ-2830)
[OJ-2830]: https://govukverify.atlassian.net/browse/OJ-2830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2830: bump hmpo-components again

- package.json
- yarn.lock
Upgrade common express to version 10.0.1
To receive the latest changes from common express
- [OJ-2977](https://govukverify.atlassian.net/browse/OJ-2977)
[OJ-2977]: https://govukverify.atlassian.net/browse/OJ-2977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2977: chore - upgrade common express v10.0.1

- .pre-commit-config.yaml
- .secrets.baseline
- deploy/template.yaml
- Update pre-commit config
- Added capacity mapping for ECS task counts 
- Removed condition on creating auto scaling policy so it applies to all envs
- This adds a new Predictive scaling policy which will scale the number of instances based on some AWS created  algorithm using the previous traffic patterns as input. See this for more information:
https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-predictive-scaling.html
- The policy is in `Forecast Mode` only so we can understand its behaviour. The predictive scaling policy will not take any action, see below in dev:
- Cost saving
- To be more Environmentally friendly
- Reliability for users
https://govukverify.atlassian.net/browse/IPS-1284
> IPS-1333: Predictive scaling for ECS in forecast mode

- src/views/kbv/question.njk
- Removed back link from questions screen
https://github.com/user-attachments/assets/68105078-6b79-4161-ad95-6ffc2ec2273f
The Back link should be hidden from all question screens in Experian KBV CRI. To prevent users returning to the `/abandon` screen after returning to the question screen
- [OJ-3012](https://govukverify.atlassian.net/browse/OJ-3012)
[OJ-3012]: https://govukverify.atlassian.net/browse/OJ-3012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3012: Fix - remove back button from question pages

- src/views/kbv/abandon.njk
- src/views/kbv/check.njk
- src/views/kbv/question.njk
Adds the required data attributes for the GA4 navigation tracker to fire on page navigation. The `data-link` attribute is set to `/undefined` after discussion with the Analytics team due to the dynamic nature of this section of the journey.
Without the added attributes, the current iteration of the navigation tracker will not fire
- [DFC-758](https://govukverify.atlassian.net/browse/DFC-758)
[DFC-758]: https://govukverify.atlassian.net/browse/DFC-758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(dfc-758): add data attributes for navigation tracking

- deploy/template.yaml
CPU increased to 2048 and memory to 4096
Due to the way that nodeJS uses the eventLoop, the performance of the container performs better if there is a second CPU able to offload some of async threads.
- [OJ-3041](https://govukverify.atlassian.net/browse/OJ-3041)
[OJ-3041]: https://govukverify.atlassian.net/browse/OJ-3041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: update cpu to 2048 and memory to 4096

- src/app/kbv/fields.js
- src/locales/cy/fields.yml
- src/locales/cy/pages.yml
- src/locales/en/fields.yml
- src/locales/en/pages.yml
- src/views/kbv/abandon.njk
New abandon screen changes:
Welsh abandon screen: 
verifying continue button spinner and is disabled when clicked:
https://github.com/user-attachments/assets/4ee07e8a-e39b-46bd-ba32-fecbbeb8b28f
Based on the changes to improve KBV abandon screen
- [OJ-2948](https://govukverify.atlassian.net/browse/OJ-2948)
[OJ-2948]: https://govukverify.atlassian.net/browse/OJ-2948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2948: Update kbv abandon screen

- src/app/kbv/controllers/question.test.js
- src/assets/scss/application.scss
- src/lib/answer-config.js
- src/lib/dynamic/question.js
- src/lib/dynamic/question.test.js
- src/locales/cy/default.yml
- src/locales/cy/pages.yml
- src/locales/en/default.yml
- src/locales/en/pages.yml
- src/presenters/answer-to-radio-item.test.js
- src/presenters/question-to-radios.js
- src/presenters/question-to-radios.test.js
- src/views/kbv/question.njk
- test/browser/pages/question.js
- test/browser/step_definitions/kbv.js
- test/mocks/mappings/abandon.json
- test/mocks/mappings/answer-error.json
- test/mocks/mappings/questions.json
- Added a new `govUkDetails` section to add text with the abandon link
- Added `or` in the second to last position of the radio button
- Updated content based on UCD changes
- Changed the last radio button "NONE OF THE ABOVE" string to use the content (once third party PR is merged)
- Change colour of hint text from black to gds grey
https://github.com/user-attachments/assets/89a22606-f3e7-48de-8707-a96fab751bc1
**Welsh translations**
To have a clear and user-friendly interface to answer security questions related to my identity, so that I can understand the question format and select an appropriate response effortlessly.
This has been reviewed by UCD
- [OJ-2947](https://govukverify.atlassian.net/browse/OJ-2947)
[OJ-2947]: https://govukverify.atlassian.net/browse/OJ-2947?atlOrigin=eyJpIjoi …
> OJ-2947: Updates to the /kbv/question Screen

- src/locales/cy/pages.yml
- src/locales/en/pages.yml
- src/views/kbv/abandon.njk
- Update html tags to use be the same as [here](https://design-system.service.gov.uk/components/radios/)
- Updated h1 to be within the form legend
- Removed blank `<p>` tags by updating the string
- [OJ-3050](https://govukverify.atlassian.net/browse/OJ-3050)
[OJ-3050]: https://govukverify.atlassian.net/browse/OJ-3050?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3050: fix - include title within the legend

- src/lib/answer-config.js
- src/presenters/answer-to-radio-item.test.js
- src/presenters/question-to-radios.test.js
- Added the `i` to the regex to allow case insensitive for noneOfTheAbove radio button
Still renders the string correctly locally:
- UAT was not rendering the correct string as the stubs were using `None of the above / does not apply` and UAT is using `NONE OF THE ABOVE / DOES NOT APPLY`
- [OJ-3071](https://govukverify.atlassian.net/browse/OJ-3071)
[OJ-3071]: https://govukverify.atlassian.net/browse/OJ-3071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3071: fix - make noneOfTheAbove regex case insensitive

- package-lock.json
- package.json
Move dependencies required for building out of dev
`npm run build` was failing after running `npm ci --production`
- [OJ-2697](https://govukverify.atlassian.net/browse/OJ-2697)
[OJ-2697]: https://govukverify.atlassian.net/browse/OJ-2697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2697: Move dependencies required for building out of dev

- Dockerfile
Change production flag to omit-dev
Fixes warning `npm WARN config production Use --omit=dev instead.` which seemed to be breaking the docker builds
Before 
After
- [OJ-2697](https://govukverify.atlassian.net/browse/OJ-2697)
[OJ-2697]: https://govukverify.atlassian.net/browse/OJ-2697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2697: Change production flag to omit-dev

- deploy/template.yaml
use stack name in KbvFrontSessionsTable name for dev environment.
so that we can create multiple FE stacks without the table name conflicting as it will already exist for the main stack.
* New session table created and the old one has been deleted in dev
* FE still works via core stub
- [OJ-3424](https://govukverify.atlassian.net/browse/OJ-3424)
[OJ-3424]: https://govukverify.atlassian.net/browse/OJ-3424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> use stack name in KbvFrontSessionsTable name

- deploy/template.yaml
- Enabled 'ReadonlyRootFilesystem' setting on the frontend host ECS container
This makes the container more secure as the filesystem (and therefore source code and system files) cannot be written to at runtime.
- [OJ-3337](https://govukverify.atlassian.net/browse/OJ-3337)
[OJ-3337]: https://govukverify.atlassian.net/browse/OJ-3337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3337: Set ReadonlyRootFilesystem on ECS container
