- package.json
- test/mocks/mappings/questions.json
- yarn.lock
Add wiremock and configuration files to represent backend API.
Mocking the API will allow the frontend to respond to all possible BE responses, including happy paths, errors and timeouts. Using the mocks inside the frontend repo allows it to be tested in isolation.
- [KBV-83](https://govukverify.atlassian.net/browse/KBV-83)
> [KBV-83] Add api mocks

- README.md
- src/app.js
- src/app/details/controllers/done.js
- src/app/kbv/controllers/load-question.js
- src/app/kbv/controllers/load-question.test.js
- src/app/kbv/controllers/question.js
- src/app/oauth2/middleware.js
- src/app/oauth2/middleware.test.js
- src/lib/axios.js
- src/lib/scenario-headers.js
- test/mocks/mappings/questions-error.json
- test/mocks/mappings/questions.json
- test/utils/mocha-helpers.js
Add support for passthrough of "scenario headers" when running in Development mode.
This will allow a mocked API to control what responses are sent back to the web browser, and thus allow easier mocking of things like alternate paths, failures or timeouts.
Axios has been instantiated onto the request object as a new instance each request. This should be examined during performance testing to ensure no adverse effects have been introduced.
> [KBV-109] Scenario headers

- .github/workflows/codeql.yml
Add codeql scanning
Test scanning
- [PLAT-78](https://govukverify.atlassian.net/browse/PLAT-78)
None
> PLAT 78 codeql scanning

- src/app/kbv/controllers/load-question.js
Fix capitalisation typo with `session_id`
> fix: capitilisation of session_id

- package.json
- src/app.js
- src/lib/config.js
- src/lib/settings.js
- src/lib/settings.test.js
- yarn.lock
Update to use `common-express` `v0.0.4` which has a breaking change of renaming `AUTHORIZATION` to `SESSION`.
`authorization_code` is appearing soon, and this naming is confusing.
> chore(deps): Update to di-ipv-cri-common-express v0.0.4

- package.json
- test/mocks/mappings/questions.json
- yarn.lock
Use `session-id` as header, not `session_id`
> chore(deps): Update to di-ipv-cri-common-express v0.0.8

- package.json
- test/mocks/mappings/questions.json
- yarn.lock
> chore(deps): Update to di-ipv-cri-common-express v0.0.9

- src/lib/dynamic-i18n.js
- src/lib/dynamic-i18n.test.js
Don't display debug hashtags on page.
Another solution will need to be determine to more easily enable testing.
> fix: Remove hashtags

- src/app/kbv/controllers/question.js
- src/lib/dynamic-i18n.js
- src/lib/dynamic-i18n.test.js
- src/locales/en/fields.yml
- test/mocks/mappings/questions.json
The previous dynamic question code was buggy, and didn't actually use the i18n files.
This refactor (without tests!) uses i18n content if found, and has a fallback of the dynamic API content.
Answers are not found in i18n content, so are passed through directly.
Browser tests show that this is passing, as does manual testing. Improved unit tests will appear in a future PR.
> Use i18n content for dynamic questions

- manifest.yml
> chore: Add DEBUG var to live debug KBV form issue

- src/locales/en/fields.yml
- test/mocks/mappings/questions.json
Add update to date translations, and adjust mock data to match.
> chore: Update mocks and i18n

- deploy/template.yaml
Use redis for session caching on frontend
Initially this provides a single node, with multi-az nodes and scaling to come.
Create redis cache and preset the frontend env var `REDIS_SESSION_URL`
Required for session caching
- [KBV-535](https://govukverify.atlassian.net/browse/KBV-535)
- `REDIS_SESSION_URL` presented to frontend.
> KBV-535: Add redis cluster

- src/app.js
- src/locales/en/default.yml
- src/views/errors/error.html
- src/views/errors/page-not-found.html
- src/views/errors/session-ended.html
- src/views/index.html
- src/views/kbv/check.html
- src/views/kbv/done.html
- src/views/kbv/question.html
Use common page templates in preparation for GTM work
> Use common templates

- deploy/template.yaml
Deployments using the long form aren't working for some reason, so attempting to reformat it with the short version.
Passes `cfn-lint` locally.
> fix: Use short forms of function to fix broken deployment

- src/app.js
- src/lib/config.js
Use the correct environment variables in the application.
> Use correct envvars in application

- src/locales/en/default.yml
- src/views/errors/error.html
- test/browser/pages/error.js
Use the common error page.
Standardising our unrecoverable error page
- [KBV-603](https://govukverify.atlassian.net/browse/KBV-603)
> KBV-603-add-unrecoverable-error

- package.json
- src/app.js
- yarn.lock
Use Helmet config to provide a default set of security headers.
This is dependent on the following PRs being merged and released:
- https://github.com/alphagov/di-ipv-cri-common-express/pull/55
- https://github.com/alphagov/di-ipv-cri-common-express/pull/61
- https://github.com/alphagov/di-ipv-cri-common-express/pull/62
- [KBV-599](https://govukverify.atlassian.net/browse/KBV-599)
> Use Helmet

- deploy/template.yaml
Create new DynamoDB table to store the kbv-front session data
Match with how the other teams are storing the front-end hmpo session data.
- [KBV-610](https://govukverify.atlassian.net/browse/KBV-610)
> KBV-610: Create dynamoDB table for kbv-front sesssion storage

- deploy/template.yaml
> Align healthcheck with other CRIs

- deploy/template.yaml
Send frontend logs to splunk.
This follows the pattern we used in the API.
- [KBV-618](https://govukverify.atlassian.net/browse/KBV-618)
> KBV-618 Send frontend logs to splunk

- src/locales/en/pages.yml
Error page title was missing from the i18n files.
> Fix error page title

- src/app/kbv/controllers/load-question.js
- src/app/kbv/steps.js
- test/browser/features/no-questions.feature
- test/mocks/mappings/no-questions.json
Add support for no question in the initial load.
A user may have a thin credit file, and thus not enough questions to be answered. This should result in the standard oauth redirect flow.
> feat: Redirect successfuly when no questions available

- src/app.js
- src/lib/config.js
Small PR to set the session timeout to 2 hours
session was 1 day.
- [KBV-683](https://govukverify.atlassian.net/browse/KBV-683)
> KBV-683-ensure-two-hour-session

- deploy/template.yaml
Output the stack name from the API template, so that it can be used in the acceptance test CodeBuild script.
> BAU Output the stack name

- src/locales/en/fields.yml
This adds i18n content for a wider range of question types.
- [KBV-698](https://govukverify.atlassian.net/browse/KBV-698)
> Add additional question translations

- deploy/template.yaml
Double desired count, memory and CPU
> OJ-878-Double desired count, memory and CPU

- .github/pull_request_template.md
- deploy/template.yaml
Remove redis
- [OJ-783](https://govukverify.atlassian.net/browse/OJ-783)
> OJ-783-remove-redis

- src/locales/cy/default.yml
- src/locales/cy/fields.yml
- src/locales/cy/pages.errors.yml
- src/locales/cy/pages.yml
Paired @jkunle @techaman-m 
We ran a script to generate the yaml files for the Welsh from a JSON file of the translation
Adds welsh content
- [OJ-897](https://govukverify.atlassian.net/browse/OJ-897)
> Add Welsh content

- src/app.js
- Changed default `i18next` cookie property to `lng` to match [auth team's usage](https://github.com/alphagov/di-authentication-frontend/blob/11bf1617e25e925ab680096f813f9c0d4876792c/src/config/i18next.ts#L8-L11).
- Added allowedLang
- Added fallbackLang
Aligning the cookies means that when the auth team set a preference for a language, that it is applied in the KBV UI as well.
- [OJ-876](https://govukverify.atlassian.net/browse/OJ-876)
> feat: Update cookie to match auth's usage

- test/browser/features/translation.feature
- test/browser/pages/error.js
- test/browser/step_definitions/language.js
The current code from address-front has been reworked to fit the KBV
structure
Using the unrecoverable error page to test switching translations is a
useful constant, even between CRIs
- [OJ-876](https://govukverify.atlassian.net/browse/OJ-876)
> test: Add browser tests for switching languages

- .husky/pre-commit
- .secrets.baseline
Added a pre-commit hook to catch secrets before they're leaked to the remote branch.
After recent secret leaks, having this extra layer in place will help mitigate future issues.
Documentation will be provided in a confluence page.
- [OJ-926](https://govukverify.atlassian.net/browse/OJ-926)
> OJ-926 Add Security  Pre-commit hook check

- .github/workflows/checks.yml
- .github/workflows/i18n.yml
i18n checks are set to run separately to the main build checks.
This allows them to be set as required or advisory without requiring pipeline changes.
> chore: Run i18n checks in separate workflow

- package.json
Allow any 16.x version of node to avoid package installation errors.
> chore: Allow any 16.x version of node

- src/locales/cy/default.yml
- src/locales/en/default.yml
Update locales file with Welsh translations
- [OJ-915](https://govukverify.atlassian.net/browse/OJ-915)
> Oj 915/update locales

- src/app/kbv/controllers/question.js
- src/app/kbv/controllers/question.test.js
- src/presenters/answer-to-radio-item.js
- src/presenters/answer-to-radio-item.test.js
- src/presenters/index.js
- src/presenters/question-to-hint.js
- src/presenters/question-to-hint.test.js
- src/presenters/question-to-legend.js
- src/presenters/question-to-legend.test.js
- src/presenters/question-to-radios.js
- src/presenters/question-to-radios.test.js
- src/views/kbv/question.html
Replace existing "dynamic questions" code with a simpler presenter pattern approach that constructs objects to give to the govuk / hmpo components.
This adds presenter transformations for:
- questionToRadios
- questionToLegend
- questionToHint
- answerToRadioItem
- [OJ-889](https://govukverify.atlassian.net/browse/OJ-889)
> Refactor: Use presenter pattern to construct radio UI

- src/views/kbv/abandon.html
- test/browser/pages/abandon.js
Submit buttons should be targetted with an ID, otherwise automated tests will get confued.
> refactor: Use continue-id for abandon form

- test/browser/features/abandon.feature
Use correct mock for abandon journey
> test: Use correct mock for abandon journey

- deploy/template.yaml
Removed old log group subscription filters.
As requested by @instantiator
- [OJ-1015](https://govukverify.atlassian.net/browse/OJ-1015)
> OJ-1015 - remove old log group subscription filter

- deploy/template.yaml
Set scaling target to 2 and max 4
Current task count is 1, this should set the minimum to 2.
> BAU-set-tasks-to-2

- deploy/template.yaml
Reverts alphagov/di-ipv-cri-kbv-front#351
we now have 2 tasks for KBV ECS front
> Revert "remove KBVOnlyOneTaskCountAlarm until we have correctly set desired/a…"

- .github/workflows/codeql.yml
- .github/workflows/i18n.yml
- .github/workflows/post-merge-to-build.yml
- .github/workflows/post-merge-to-dev.yml
- .secrets.baseline
Address, Fraud and KBV SSM parameter deployment workflows have been updated:
* Deprecated GHA actions have been updated to the newer versions.
* setup-sam fix has been applied
Primarily to apply the setup-sam fix so that the workflows are not broken.
(https://github.com/aws/aws-sam-cli/issues/4527)
Secondly in preparation for GitHub to remove the deprecated functionality.
- [OJ-1146](https://govukverify.atlassian.net/browse/OJ-1146)
[OJ-1146]: https://govukverify.atlassian.net/browse/OJ-1146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1146 workflow deprecations and sam fix

- src/locales/cy/fields.yml
- src/locales/en/fields.yml
Update the unhappy path content for users to assist them in completing their journey.
The `fields.yml` files have been updated with new text.
This is part of an overall harmonisation of the unhappy path content patterns by content designers.
- [PYIC-2185](https://govukverify.atlassian.net/browse/PYIC-2185)
[PYIC-2185]: https://govukverify.atlassian.net/browse/PYIC-2185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PYIC-2185 Update unhappy path content

- src/lib/config.js
Update path to explicitly use a folder. This will allow a simpler WAF rule to be used.
> Update path to explicitly use folder

- .github/workflows/checks.yml
> Dependabot update for push config

- .github/workflows/checks.yml
> check.yml with history

- .nycrc.yml
Raise the code coverage failure level to the minimum as set in the watermark
> chore: Raise code coverage to 60% (minimum watermark)

- deploy/template.yaml
template.yaml
In order to do effective performances tests that accurately reflect how high volume would effect production - we need our testing environment to match that of production.
- [OJ-1643](https://govukverify.atlassian.net/browse/OJ-1643)
[OJ-1643]: https://govukverify.atlassian.net/browse/OJ-1643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update template.yaml [Do not merge]

- src/locales/en/fields.yml
BAU: update question to match content design
This PR updates content to match the format requested by the content designers.
Two questions describe the requirements for the user more accurately.
The change was discovered when content was audited for the Welsh translation.
> BAU: update question to match content design

- deploy/template.yaml
template.yaml include auto scaling to kbv
> Added auto scaling

- deploy/template.yaml
- VpceId needs to be included as part of the API_BASE_URL for frontend to be able to talk to the API in the VPC
Stack drift in KBV
> FIX VPC ISSUE: Include VpceId in the Api base url

- deploy/template.yaml
Reverts govuk-one-login/ipv-cri-kbv-front#725
Use enable private DNS instead of hard-coding to imports
> Revert "FIX VPC ISSUE: Include VpceId in the Api base url"

- deploy/template.yaml
- src/app.js
- src/lib/config.js
Add config for log level differences between dev/build and staging/production/integration
> Add support for overriding log level

- package.json
- src/app.js
- src/locales/cy/default.yml
- src/locales/en/default.yml
- yarn.lock
- Upgrade to @govuk-one-login/di-ipv-cri-common-express@3.2.0
- Update content keys due to breaking change
> chore: Upgrade to @govuk-one-login/di-ipv-cri-common-express@3.2.0

- CODEOWNERS
Update Codeowners with govuk-one-login teams
> chore: Update Codeowners with govuk-one-login teams

- deploy/template.yaml
- package.json
Max capacity for auto scaling has been increased to 60, to match what is in core: https://github.com/govuk-one-login/ipv-core-front/blob/6199710a90ca8f68662ff0e8961dd2154294f28b/deploy/template.yaml#L457C10-L457C10
During perf test, the current capacity was hit and the system was using 100% CPU. This causes HTTP 500 errors.
The fix recommended by perf team is to increase this limit.
- [OJ-1684](https://govukverify.atlassian.net/browse/OJ-1684)
[OJ-1684]: https://govukverify.atlassian.net/browse/OJ-1684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1684: Increased MaxCapacity for auto scaling

- .github/workflows/post-merge-to-build.yml
- .github/workflows/post-merge-to-dev.yml
- .pre-commit-config.yaml
- .secrets.baseline
- CODEOWNERS
- Dockerfile
- deploy/template.yaml
IPS-294 Added Dynatrace Integration
Updated Codeowners
Added Dynatrace layer to Dockerfile
Updated Template
Added checkov and cfn-lint to pre-commit hooks
Fixed github workflows ordering
modified:   .github/workflows/post-merge-to-build.yml
modified:   .github/workflows/post-merge-to-dev.yml
modified:   .pre-commit-config.yaml
modified:   .secrets.baseline
modified:   CODEOWNERS
modified:   Dockerfile
modified:   deploy/template.yaml
IPS-294 Added Dynatrace Integration
Updated Codeowners
Added Dynatrace layer to Dockerfile
Updated Template
Added checkov and cfn-lint to pre-commit hooks
Fixed github workflows ordering
- [IPS-294](https://govukverify.atlassian.net/browse/IPS-294)
[IPS-294]: https://govukverify.atlassian.net/browse/IPS-294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …
> IPS-294 Added Dynatrace Integration

- .github/workflows/post-merge-to-dev.yml
Added `workflow_dispatch:` to `post-merge-to-dev.yml`
So we can run the deployment manually for testing.
> BAU: Added `workflow_dispatch`

- deploy/template.yaml
Added step scaling configuration into `template.yaml`. 
This has been referenced from what is done in address: https://github.com/govuk-one-login/ipv-cri-address-front/blob/main/deploy/template.yaml
To pass performance testing.
- [OJ-1684](https://govukverify.atlassian.net/browse/OJ-1684)
[OJ-1684]: https://govukverify.atlassian.net/browse/OJ-1684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1684: Added step scaling

- .secrets.baseline
- deploy/template.yaml
`template.yaml` added health checking configs to `LoadBalancerListenerTargetGroupECS` this is to match what core has done. It's required to hit performance testing requirements. 
https://govukverify.atlassian.net/wiki/spaces/DID/pages/3711140164/AWS+Fargate+Scaling+Capacity+Issues?focusedCommentId=3719233649
- [OJ-1684](https://govukverify.atlassian.net/browse/OJ-1684)
[OJ-1684]: https://govukverify.atlassian.net/browse/OJ-1684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1684: Added health checking to `LoadBalancerListenerTargetGroupECS`

- sonar-project.properties
IPS-311 GitHub Org Sonar Migration
IPS-311 GitHub Org Sonar Migration
- [IPS-311](https://govukverify.atlassian.net/browse/IPS-311)
[IPS-311]: https://govukverify.atlassian.net/browse/IPS-311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-311 GitHub Org Sonar Migration

- .nycrc.yml
- sonar-project.properties
Ignore form-wizard config in sonar.properties
> test: Add config filepaths to sonar.exclusions

- package.json
- yarn.lock
Reverting hmpo-components 6.0 due to an issue rendering content 
> Revert 6.x hmpo-components due to radios locales issue

- src/locales/cy/default.yml
- src/locales/en/default.yml
Update footer content to match other parts of the journey. 
Two yaml files are updated to match IPV Core’s content – the extra content notifies users that the link opens in a new window.
- [CNUCD-262](https://govukverify.atlassian.net/browse/CNUCD-262)
[CNUCD-262]: https://govukverify.atlassian.net/browse/CNUCD-262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CNUCD-262 Update footer content for English and Welsh

- package.json
- src/views/components/onPageLoad/macro.njk
- src/views/components/onPageLoad/template.njk
- src/views/errors/error.njk
- src/views/errors/page-not-found.njk
- src/views/kbv/abandon.njk
- src/views/kbv/check.njk
- src/views/kbv/question.njk
- yarn.lock
- Adds in the OPL template and macro files
- Adds OPL tracking to each page
- To enable on page load GA4 tracking
- [DFC-323](https://govukverify.atlassian.net/browse/DFC-323)
[DFC-323]: https://govukverify.atlassian.net/browse/DFC-323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DFC-323] - Implement OPL macro for analytics tracking

- package.json
- yarn.lock
Updates the analytics package version to latest
The latest package release contains several bug fixes required by the analytics team to unblock their QA. The package has also been renamed to improve compliance.
This is the first major version push of the package, from this point forward dependabot should pick up new version releases.
[DFC-555](https://govukverify.atlassian.net/browse/DFC-555)
[DFC-555]: https://govukverify.atlassian.net/browse/DFC-555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DFC-555: Update analytics package to v1.0.3

- package.json
- src/app.js
- src/assets/scss/application.scss
- yarn.lock
Update language toggle dependency, and use new nujucks global
- [OJ-2563](https://govukverify.atlassian.net/browse/OJ-2563)
[OJ-2563]: https://govukverify.atlassian.net/browse/OJ-2563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Use updated language toggle and cri-common-express

- deploy/template.yaml
Enabled Welsh Toggle for Dev, Build and Stage environment for E2E testing
To run full end to end testing in the staging RP env
- [OJ-2596](https://govukverify.atlassian.net/browse/OJ-XXXX)
[OJ-2596]: https://govukverify.atlassian.net/browse/OJ-2596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Enable Welsh Toggle in all env apart from Prod and Int

- deploy/template.yaml
Deployments into staging were failing with an error of:
```
22 May 2024 at 15:31 (UTC+1:00)	throw Error(`default level:${defaultLevel} must be included in custom levels`)	app
22 May 2024 at 15:31 (UTC+1:00)	^	app
22 May 2024 at 15:31 (UTC+1:00)	Error: default level:request must be included in custom levels	app
22 May 2024 at 15:31 (UTC+1:00)	at assertDefaultLevelFound (/app/node_modules/pino/lib/levels.js:194:11)	app
```
This is due to Pino inside the @govuk-one-login/frontend-passthrough-headers module   [being configured without custom levels](https://github.com/govuk-one-login/frontend-passthrough-headers/blob/main/src/utils/logger.ts#L5C62-L5C66). This causes a runtime error on deplyment when the `LOG_LEVEL` is set to an unexpected value.
As a quick fix, the LOG_LEVEL can be slightly …
> Update default LOG_LEVEL to warn for staging and higher environments

- package.json
- yarn.lock
[OJ-2571] Accessibility Fix - Focus on Error Summary
updated di-ipv-cri-common-express to include the fix
[OJ-2571](https://govukverify.atlassian.net/browse/OJ-2571)
[OJ-2571]: https://govukverify.atlassian.net/browse/OJ-2571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> update common express to include the fix

- package.json
- yarn.lock
- Upgrade axios package to v1.x
- Upgrade wait-on package to use transitive dependency of axios 1.x 
> chore: Use most recent versions of axios in axios and wait-on packages

- package.json
- yarn.lock
Update @govuk-one-login/frontend-analytics to v2.0.0 to improve GA4 usage
- GA4 is only currently enabled in Dev / Build / Staging
- [OJ-2636](https://govukverify.atlassian.net/browse/OJ-2636)
[OJ-2636]: https://govukverify.atlassian.net/browse/OJ-2636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: Update @govuk-one-login/frontend-analytics to v2.0.0

- .github/workflows/post-merge-to-build.yml
- .github/workflows/post-merge-to-dev.yml
[IPS-819] PR Title --> Ips 819 - upload action ecr updated to 1.2.6
post merge to build and post merge to dev updated with upload action ecr version 1.2.6. v was required with the newer version
updated to latest version
N/A
testing done in dev, see [IPS-819](https://govukverify.atlassian.net/browse/IPS-819) ticket to view this
[IPS-819](https://govukverify.atlassian.net/browse/IPS-819)
[IPS-819]: https://govukverify.atlassian.net/browse/IPS-819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-819]: https://govukverify.atlassian.net/browse/IPS-819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-819]: https://govukverify.atlassian.net/browse/IPS-819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …
> IPS-819 upload action ecr updated to v1.2.6

- deploy/template.yaml
Set ga4Disabled to false for integration and prod.
Enable GA4 Toggle in Production
- [OJ-2648](https://govukverify.atlassian.net/browse/OJ-2648)
[OJ-2648]: https://govukverify.atlassian.net/browse/OJ-2648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2648: Enable ga4 in integration and prod

- package.json
- yarn.lock
OJ-2674: Upgrade analytics package to include bug fix for GA4
> Upgrades analytics package

- package.json
- yarn.lock
> OJ-2674: Upgrades common express

- deploy/template.yaml
- Enable block WAF and associate with the load balancer
- Disable the count WAF which was deployed with the CloudFront
- Enable the block WAF 
- Associate the block with Load balancer
- Count WAF been added during CloudFront deployment.
- Having found CloudFront working, the count waf need to be disabled to enable the block WAF
- Disable the count association with Load balancer and enable the block waf association with load balancer
- Verify the CloudFront traffic using count WAF
- [IPS-863](https://govukverify.atlassian.net/browse/IPS-863)
[IPS-863]: https://govukverify.atlassian.net/browse/IPS-863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-863: Enabled Block WAF Association with Load balancer

- deploy/template.yaml
IPS-536 Canary ECS Deployments for KBV
Added the Following Paramaters:
* CodeSigningConfigArn
* DeploymentStrategy
Added the Following Conditions:
* UseCodeSigning
* UseCanaryDeployment
Added The following Resources:
* SecondLoadBalancerListenerTargetGroupECS
* FrontTargetGroup5xxPercentErrors
* ECSBlueGreenDeploymentStack
Removed the condition to specific environments,
this has to be done across all of the environments in 1 go as it is two
stage dependant and trying to do a staggered approach will do more harm
than good as new environments are introduced it will try to rollback
changes in the previous environments which in turn will break them.
IPS-536 Canary Implementation - Stage 1 Deployment
Updated the template - added Security Groups and Network Interfaces
to the Nested Stack. This …
> IPS-536 Canary ECS Deployments for KBV - Deployment

- deploy/template.yaml
- package.json
- src/app.js
- yarn.lock
Added `frontend-vital-signs` package and initialised it within `app.js`
Added metrics for the logging for `frontend-vital-signs`
The log messages provided by the `frontend-vital-signs` package is to help us monitor performance metrics such as average response times and how many requests we get per second.
- [OJ-2761](https://govukverify.atlassian.net/browse/OJ-2761)
[OJ-2761]: https://govukverify.atlassian.net/browse/OJ-2761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2761: Add vital signs package

- src/locales/cy/fields.yml
- src/locales/en/fields.yml
3 new questions are added to the KBV Question pool
- [OJ-2690](https://govukverify.atlassian.net/browse/OJ-2690)
[OJ-2690]: https://govukverify.atlassian.net/browse/OJ-2690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2690: Add translations for 3 new questions

- test/browser/features/errors.feature
- test/mocks/mappings/questions-error.json
Fix mock question-error scenario and add a new test to cover it
Because it was broken
> Fix mock and add new scenario

- package.json
- yarn.lock
Added yarn-audit-fix to help fixing/identifying vulnerabilites
Ran yarn-audit-fix to update yarn.lock
Fix vulnerabitlies: https://github.com/govuk-one-login/ipv-cri-kbv-front/security/dependabot/28
> BAU fix vulnerabitlies

- package.json
- yarn.lock
Upgrade dependencies
https://github.com/govuk-one-login/ipv-cri-kbv-front/security/dependabot/52
- [OJ-2900](https://govukverify.atlassian.net/browse/OJ-2900)
[OJ-2900]: https://govukverify.atlassian.net/browse/OJ-2900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2900: Upgrade dependencies

- package.json
- yarn.lock
common express upgraded to 8.1.0
To include performance fix
- [OJ-2874](https://govukverify.atlassian.net/browse/OJ-2874)
[OJ-2874]: https://govukverify.atlassian.net/browse/OJ-2874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2874: Bump common express

- Dockerfile
Revert dynatrace COPY line change
From here https://github.com/govuk-one-login/ipv-cri-kbv-front/pull/1167
Failing to deploy the main dockerfile and this is the only real change from the original
- [OJ-2697](https://govukverify.atlassian.net/browse/OJ-2697)
[OJ-2697]: https://govukverify.atlassian.net/browse/OJ-2697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2697: Revert dynatrace COPY line change

- Dockerfile
Fixed stages in Dockerfile
dynatrace and builder stages were in wrong order meaning the copying wasn't working as expected
- [OJ-2697](https://govukverify.atlassian.net/browse/OJ-2697)
[OJ-2697]: https://govukverify.atlassian.net/browse/OJ-2697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2697: Fix stages

- package-lock.json
- package.json
- src/app.js
- src/lib/config.js
Removed existing overload-protection, replaced with common-express implementation.
Remove custom logic. 
- [OJ-3121](https://govukverify.atlassian.net/browse/OJ-3121)
[OJ-3121]: https://govukverify.atlassian.net/browse/OJ-3121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3121: Use common-express overload-protection

- deploy/template.yaml
Change SupportManualURL to mapping
Because params cannot easily be updated
- [OJ-3214](https://govukverify.atlassian.net/browse/OJ-3214)
[OJ-3214]: https://govukverify.atlassian.net/browse/OJ-3214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3214: Change SupportManualURL to mapping

- .github/workflows/code-quality.yml
- .github/workflows/run-browser-tests.yml
- .github/workflows/run-unit-tests.yml
- .github/workflows/scan-repo.yml
Upgrade github-actions to latest version
Upgraded addresses because there was a warning, wanted to keep all the fronts on the same version
> BAU: Upgrade github-actions to latest version

- package-lock.json
- package.json
Bump axios and wait-on, add form-data overrides
form-data vulnerability was fixed in axios 1.11.0 and wait-on 8.0.4
https://github.com/axios/axios/pull/6970
https://github.com/jeffbski/wait-on/pull/174
- [OJ-3271](https://govukverify.atlassian.net/browse/OJ-3271)
[OJ-3271]: https://govukverify.atlassian.net/browse/OJ-3271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3271: Bump axios and wait-on
